services:
  db:
    image: aldejosa/sqlPinacoteca:v1
    container_name: contenedorMiCine
    ports:
      - "3306:3306"
    networks:
      - mi-red

  app:
    image: aldejosa/mi_app_cine:v1
    container_name: contenedorMiApp
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge
